    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: f6sny-next-frontend
    spec:
      selector:
        matchLabels:
          app: f6sny-next-frontend
          component: frontend
      template:
        metadata:
          labels:
            app: f6sny-next-frontend
            component: frontend
        spec:
          containers:
          - name: f6sny-next-frontend
            image: ghcr.io/f6sny/www.f6sny.com:latest
            ports:
              - containerPort: 3000
            envFrom:
              - secretRef:
                  name: f6sny-frontend-secrets
            resources:
              requests:
                cpu: "100m"        # light baseline
                memory: "192Mi"    # enough for boot
              limits:
                cpu: "500m"
                memory: "384Mi"
            readinessProbe:
              httpGet:
                path: /api/health
                port: 3000
              initialDelaySeconds: 30   # faster SSR boot

              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
            livenessProbe:
              httpGet:
                path: /api/health
                port: 3000
              initialDelaySeconds: 60   # give time for SSR to warm up
              periodSeconds: 20
              timeoutSeconds: 5
              failureThreshold: 3
