apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: f6sny-frontend-secrets
  namespace: f6sny
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: f6sny-frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: NEXT_PUBLIC_API_URL
      remoteRef:
        key: f6sny/env-vars
        property: NEXT_PUBLIC_API_URL
    - secretKey: API_URL
      remoteRef:
        key: f6sny/env-vars
        property: API_URL

