apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: f6sny-next-frontend-hpa
  namespace: f6sny
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: f6sny-next-frontend
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
