export * from './api.d'
export * from './joke.d'
export * from './page.d'
export * from './sidebar.d'
export * from './tag.d'
export * from './auth.d'
export * from './comment.d'
export * from './ui.d'